# Node.js with React - Security Scans, Report Generation & Cleanup
trigger:
  - Development

pool:
  vmImage: ubuntu-latest

steps:
  # ✅ Cleanup Step to Remove Old Files Before Execution
  - script: |
      echo "Cleaning up old files from previous runs..."
      rm -rf $(Build.ArtifactStagingDirectory)/*
      rm -rf dependency-check*
      rm -rf node_modules
      npm cache clean --force
    displayName: 'Pre-Cleanup: Remove Old Build Files & Free Memory'

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm cache clean --force
      npm install --force
    displayName: 'Install Dependencies'

  # ✅ Build React Application
  - script: |
      npm run build
    displayName: 'Build React Application'

  # ✅ Ensure web.config is added
  - script: |
      mkdir -p $(Build.ArtifactStagingDirectory)/build

    displayName: 'Ensure web.config is Added to Build Folder'

  # ✅ Copy Build Files to Staging Directory
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/build'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/build'
    displayName: 'Copy Build Files to Staging Directory'

  # ✅ Archive Build Output
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    displayName: 'Archive Build Output'

  # ✅ Publish Build Artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'drop'
    displayName: 'Publish Build Artifact'


